.PHONY: build test test-integration lint clean docker-build proto-gen run kind-up kind-down deploy

# Variables
BINARY_SERVER = bin/kora-server
BINARY_CONSOLIDATE = bin/kora-consolidate
BINARY_CLI = bin/kora
DOCKER_IMAGE = kora/kora
DOCKER_TAG = dev
KIND_CLUSTER = kora-dev

# Build
build:
	go build -o $(BINARY_SERVER) ./cmd/server
	go build -o $(BINARY_CONSOLIDATE) ./cmd/consolidate
	go build -o $(BINARY_CLI) ./cmd/cli

# Test
test:
	go test ./... -v -race -cover

# Integration tests for the graph repository. These run real Cypher against a
# real Apache AGE instance, which is the only way to catch queries that compile
# in Go but are malformed openCypher. Skipped by `make test`, which stays
# hermetic.
test-integration:
	docker compose up -d postgres
	@until docker compose exec -T postgres pg_isready -U kora >/dev/null 2>&1; do sleep 1; done
	KORA_TEST_DATABASE_URL="postgres://kora:kora@localhost:5432/kora?sslmode=disable" \
		go test ./internal/graph/... -count=1 -race -v

test-coverage:
	go test ./... -coverprofile=coverage.out -covermode=atomic
	go tool cover -html=coverage.out -o coverage.html

# Lint
lint:
	golangci-lint run ./...

# Proto generation
proto-gen:
	@mkdir -p api/gen/kora/v1
	PATH="$(HOME)/go/bin:$(PATH)" protoc \
		--go_out=api/gen --go_opt=paths=source_relative \
		--go-grpc_out=api/gen --go-grpc_opt=paths=source_relative \
		--grpc-gateway_out=api/gen --grpc-gateway_opt=paths=source_relative \
		-I api/proto \
		api/proto/kora/v1/memory.proto \
		api/proto/kora/v1/session.proto \
		api/proto/kora/v1/health.proto

# Docker
docker-build:
	docker build -t $(DOCKER_IMAGE):$(DOCKER_TAG) .

# Run locally (requires PostgreSQL + AGE running)
run:
	go run ./cmd/server

# Kind cluster management
kind-up:
	kind create cluster --name $(KIND_CLUSTER) --config deploy/kind-config.yaml
	@echo "Kind cluster '$(KIND_CLUSTER)' created"

kind-down:
	kind delete cluster --name $(KIND_CLUSTER)

kind-load: docker-build
	kind load docker-image $(DOCKER_IMAGE):$(DOCKER_TAG) --name $(KIND_CLUSTER)

# Local dev credentials.
#
# The chart ships no default password or API key -- a default in a public chart
# is a published credential -- so a local deployment has to generate its own.
# They are written to .dev-credentials (gitignored) and reused across deploys,
# because regenerating the Postgres password on every `make deploy` would leave
# it disagreeing with the one already initialised in the PVC.
DEV_CREDS := .dev-credentials

$(DEV_CREDS):
	@umask 077 && { \
	  echo "# Generated by make. Local kind cluster only. Never commit."; \
	  echo "DEV_PG_PASSWORD=$$(openssl rand -hex 16)"; \
	  echo "DEV_API_KEY=ctx0_$$(openssl rand -hex 6)_$$(openssl rand -hex 24)"; \
	} > $@
	@echo "Generated $(DEV_CREDS)"

.PHONY: dev-credentials
dev-credentials: $(DEV_CREDS)
	@cat $(DEV_CREDS)

# Deploy to kind cluster
deploy: kind-load $(DEV_CREDS)
	@. ./$(DEV_CREDS) && \
	helm upgrade --install kora ./charts/kora -n kora --create-namespace \
	  --set postgres.password="$$DEV_PG_PASSWORD" \
	  --set auth.apiKeys="$$DEV_API_KEY"
	@echo "Kora deployed to kind cluster"
	@echo "API key: $$(. ./$(DEV_CREDS) && echo $$DEV_API_KEY)"

undeploy:
	helm uninstall kora -n kora

# Clean
clean:
	rm -rf bin/ coverage.out coverage.html api/gen/

# Help
help:
	@echo "Available targets:"
	@echo "  build          - Build all binaries"
	@echo "  test           - Run all tests"
	@echo "  lint           - Run linter"
	@echo "  proto-gen      - Generate Go code from proto files"
	@echo "  docker-build   - Build Docker image"
	@echo "  run            - Run server locally"
	@echo "  kind-up        - Create kind cluster"
	@echo "  kind-down      - Delete kind cluster"
	@echo "  deploy         - Deploy to kind cluster"
	@echo "  clean          - Remove build artifacts"
